feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true

logging:
  level:
    org:
      springframework: info
    root: info
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
server:
  port: 53010
spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service
          predicates:
            # 匹配路径转发
            - Path=/order/**
        - id: order-service
          uri: http://uaa-service
          predicates:
            # 匹配路径转发
            - Path=/uaa/**
    nacos:
      config:
        username: nacos
        password: nacos
        namespace: spring-security-oauth2
      discovery:
        username: nacos
        password: nacos
        namespace: spring-security-oauth2
      server-addr: 192.168.241.129:8848
    config:
      allow-override: true
      override-none: true
      override-system-properties: true