feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true

logging:
  level:
    org:
      springframework: info
    root: debug
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
server:
  port: 53010
spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
#            allowedOrigins: "*"
#            allowedHeaders: "*"
#            allowedMethods: "*"
            allowCredentials: true
            allowedOriginPatterns: "*"
            maxAge: 1800
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            # 匹配路径转发
            - Path=/order/**
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            # 匹配路径转发
            - Path=/uaa/**
      httpclient:
        response-timeout: 60S
        connect-timeout: 10
    nacos:
      config:
        server-addr: 192.168.241.129:8848
        namespace: spring-security-oauth2
        username: nacos
        password: nacos
      discovery:
        server-addr: 192.168.241.129:8848
        namespace: spring-security-oauth2
        username: nacos
        password: nacos
    config:
      allow-override: true
      override-none: true
      override-system-properties: true