// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello-world-service.proto

package wjc.dubbo.s001.helloworld.api;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wjc.dubbo.s001.helloworld.api.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
