// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello-world-service.proto

package wjc.dubbo.s001.helloworld.api;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wjc.dubbo.s001.helloworld.api.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
